#!/bin/bash
# download-model.sh - Download model from Hugging Face

set -euo pipefail

ENV_FILE=".env"
KEY_1="NEURON_RT_NUM_CORES"
KEY_2="TENSOR_PARALLEL_SIZE"

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../../nki-llama.config"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}Downloading model from Hugging Face...${NC}"

# Check HF token
if [[ -z "${HF_TOKEN:-}" ]]; then
    echo -e "${YELLOW}HF_TOKEN not set${NC}"
    echo "Get a token at: https://huggingface.co/settings/tokens"
    read -p "Enter your Hugging Face token: " HF_TOKEN
    if [[ -z "$HF_TOKEN" ]]; then
        echo -e "${RED}Error: HF_TOKEN is required${NC}"
        exit 1
    fi
fi

# Ensure huggingface-cli is installed
pip install -q huggingface_hub[cli]

# Ensure transformers < 4.50 (needed by Neuron hf_adapter)
python - <<'PY'
import subprocess, pkg_resources, sys
req = "4.50.0"
try:
    ver = pkg_resources.get_distribution("transformers").version
except pkg_resources.DistributionNotFound:
    ver = ""
if not ver or pkg_resources.parse_version(ver) >= pkg_resources.parse_version(req):
    print("Installing transformers<%s …" % req)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", f"transformers<{req}"])
PY

# Determine the instance type before deciding the model
source "${SCRIPT_DIR}/../../../src/inference/scripts/instance_type.sh"

if [ "$EC2_INSTANCE_TYPE" == "trn1.2xlarge" ]; then
    # Check if MODEL_ID_1B is set
    if [ -z "$MODEL_ID_1B" ]; then
        echo "Error: MODEL_ID_1B environment variable is not set!"
        echo "Please make sure MODEL_ID_1B is defined in your .env file"
        exit 1
    fi

    export MODEL_ID="$MODEL_ID_1B"
    export MODEL_NAME="$MODEL_NAME_1B"

    # Set NeuronCore number
    VALUE="2"
    # Check if key exists and update it, otherwise add it - NEURON_RT_NUM_CORES
    if grep -q "^${KEY_1}=" "$ENV_FILE" 2>/dev/null; then
        # Key exists, update it
        sed -i "s/^${KEY_1}=.*/${KEY_1}=${VALUE}/" "$ENV_FILE"
    else
        # Key doesn't exist, add it
        echo "${KEY_1}=${VALUE}" >> "$ENV_FILE"
    fi

    # Check if key exists and update it, otherwise add it - TENSOR_PARALLEL_SIZE
    if grep -q "^${KEY_2}=" "$ENV_FILE" 2>/dev/null; then
        # Key exists, update it
        sed -i "s/^${KEY_2}=.*/${KEY_2}=${VALUE}/" "$ENV_FILE"
    else
        # Key doesn't exist, add it
        echo "${KEY_2}=${VALUE}" >> "$ENV_FILE"
    fi

    echo "🚀 Model: Downloading Llama-3.2 1B..."
elif [ "$EC2_INSTANCE_TYPE" == "trn1.32xlarge" ]; then
    # Check if MODEL_ID_8B is set
    if [ -z "$MODEL_ID_8B" ]; then
        echo "Error: MODEL_ID_8B environment variable is not set!"
        echo "Please make sure MODEL_ID_8B is defined in your .env file"
        exit 1
    fi

    export MODEL_ID="$MODEL_ID_8B"
    export MODEL_NAME="$MODEL_NAME_8B"

    # Set NeuronCore number
    VALUE="8"
    # Check if key exists and update it, otherwise add it - NEURON_RT_NUM_CORES
    if grep -q "^${KEY_1}=" "$ENV_FILE" 2>/dev/null; then
        # Key exists, update it
        sed -i "s/^${KEY_1}=.*/${KEY}=${VALUE}/" "$ENV_FILE"
    else
        # Key doesn't exist, add it
        echo "${KEY_1}=${VALUE}" >> "$ENV_FILE"
    fi

    # Check if key exists and update it, otherwise add it - TENSOR_PARALLEL_SIZE
    if grep -q "^${KEY_2}=" "$ENV_FILE" 2>/dev/null; then
        # Key exists, update it
        sed -i "s/^${KEY_2}=.*/${KEY_2}=${VALUE}/" "$ENV_FILE"
    else
        # Key doesn't exist, add it
        echo "${KEY_2}=${VALUE}" >> "$ENV_FILE"
    fi

    echo "🚀 Model: Downloading Llama-3 8B..."
else
    echo "Error: Unsupported instance type: $EC2_INSTANCE_TYPE"
    echo "This script requires either trn1.2xlarge or trn1.32xlarge"
    exit 1
fi

# Create models directory
mkdir -p "$NKI_MODELS"

# Download model
echo "Downloading ${MODEL_ID} to ${NKI_MODELS}/${MODEL_NAME}"
huggingface-cli download \
    --token "$HF_TOKEN" \
    "$MODEL_ID" \
    --local-dir "${NKI_MODELS}/${MODEL_NAME}"

# Export variables to environment for other scripts to use
echo "Exporting model variables to environment..."
echo "MODEL_NAME=$MODEL_NAME"
echo "MODEL_ID=$MODEL_ID"

# Create a file to store these variables for other scripts
cat > "${SCRIPT_DIR}/model_env.sh" << EOF
#!/bin/bash
# Auto-generated by download-model.sh
# Contains model environment variables for other scripts

export MODEL_NAME="${MODEL_NAME}"
export MODEL_ID="${MODEL_ID}"
EOF

chmod +x "${SCRIPT_DIR}/model_env.sh"
echo "✅ Created model environment file at: ${SCRIPT_DIR}/model_env.sh"

echo -e "${GREEN}✓ Model downloaded successfully${NC}"
echo "Location: ${NKI_MODELS}/${MODEL_NAME}"

# Save configuration hint
if [[ -z "${HF_TOKEN:-}" ]]; then
    echo
    echo "To save your token, add to .env file:"
    echo "HF_TOKEN=$HF_TOKEN"
fi